# Generated by Django 5.2.6 on 2025-09-15 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0004_alter_favorite_adv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='adv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisements.advertisement'),
        ),
    ]
