# Generated by Django 5.2.5 on 2025-08-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_measurement_temperature_sensor_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
